name: Terraform workflow

on:
  push:
     branches: 
     - main

env:
  region: ap-south-1

jobs:
   AWS_Configure:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v3
       - name: List of files  
         run: pwd
         
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ env.region }}
           
       - name: List of buckets
         run: aws s3 ls
